on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: "macos-13"
    steps:
      - run: |
          wget https://desktop.docker.com/mac/main/amd64/Docker.dmg
          sudo hdiutil attach Docker.dmg
          sudo /Volumes/Docker/Docker.app/Contents/MacOS/install
          sudo hdiutil detach /Volumes/Docker
      - run: docker run --rm -i golang pwd
