on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Docker
      run: |
        brew update
        brew install docker
        brew install docker-machine
        brew cask install virtualbox
        docker-machine create --driver virtualbox default
        docker-machine ls
        docker-machine start default
        docker-machine ls
        eval $(docker-machine env default)
        docker run hello-world

