on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: "macos-12"
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'
      - name: Install hugo
        run: CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@v0.112.1
      - run: hugo help
