on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: "macos-13"
    steps:
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v1
      - run: docker run --rm -i golang pwd
