on: [push, pull_request]
name: Test
env:
  HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - run: brew update

      # run: |
      #   brew update
      #   brew install docker
      #   brew install docker-machine
      #   docker-machine create --driver virtualbox default
      #   docker-machine ls
      #   docker-machine start default
      #   docker-machine ls
      #   eval $(docker-machine env default)
      #   docker run hello-world


        # brew cask install virtualbox
