on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: "macos-12"
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.112.1'
          extended: true
      - run: hugo help
