# https://www.robinwieruch.de/docker-macos

on: [push, pull_request]
name: Test
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run: brew cask install docker
    - run: xattr -d -r com.apple.quarantine /Applications/Docker.app
    - run: sudo /bin/cp /Applications/Docker.app/Contents/Library/LaunchServices/com.docker.vmnetd /Library/PrivilegedHelperTools
    - run: sudo /bin/cp /Applications/Docker.app/Contents/Resources/com.docker.vmnetd.plist /Library/LaunchDaemons/
    - run: sudo /bin/chmod 544 /Library/PrivilegedHelperTools/com.docker.vmnetd
    - run: sudo /bin/chmod 644 /Library/LaunchDaemons/com.docker.vmnetd.plist
    - run: sudo /bin/launchctl load /Library/LaunchDaemons/com.docker.vmnetd.plist
    - run: ls /Applications
    - run: ./run.sh
    - run: git clone https://github.com/play-with-docker/play-with-docker
    - run: docker swarm init
    - run: cd play-with-docker
    - run: docker pull franela/dind
    - run: go mod vendor
    - run: docker-compose up -d
    - run: sleep 60
    - run: docker-compose logs
    - run: curl http://localhost


    # Previously working port mapping stuff
    - run: docker run --rm -v /etc:/blah golang ls /blah
    - run: docker pull nginxdemos/hello
    - run: docker run --rm -d -p 80:80 nginxdemos/hello
    - run: sleep 10

    # - run: touch README.md
    # - run: brew install docker
    # - run: brew install docker-machine
    # - run: brew install docker-compose
    # - run: docker-machine create --driver virtualbox default
    # - run: docker-machine ls
    # - run: eval $(docker-machine env default) && docker run --rm -v create-your-first-guide:/var --privileged playwithgo/create-your-first-guide docker version

