on: [push, pull_request]
name: Test
env:
  HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - run: brew update
    - run: brew install docker
    - run: brew install docker-machine
    - run: docker-machine create --driver virtualbox default
    - run: docker-machine start default
    - run: docker-machine ls
    - run: eval $(docker-machine env default) && docker run hello-world

        # brew cask install virtualbox
